### ISSUE TITLE
bug: Config does not support inheritance for mappers

### ISSUE THREAD

**Issue by peterspiro** [meltano/meltano#8222]
### Meltano Version

3.1.0

### Python Version

3.9

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

OSX

### Description

I’d like to use mapper configs that inherit from `meltano-map-transformer`, so that I can distribute them across multiple yaml files, which I already do for my extractors and loaders.

However, the config below produces the error:
```
Error: Ambiguous mapping name rename_column, found multiple matches.
```
even though the mapping is only declared once, in the inheriting section.

I don't get the error if I omit inheritance and instead place the `mappings` sub-section in the `meltano.yml` config section, omitting the second section.

### Code

```python
# in meltano.yml:

  mappers:
    - name: meltano-map-transformer
      pip_url: "git+https://github.com/MeltanoLabs/meltano-map-transform.git"
      executable: meltano-map-transform

# in a different file:

  mappers:
    - name: transform-columns
      inherit_from: meltano-map-transformer
      mappings:
        - name: rename_column
          config:
            stream_maps:
              stream_name:
                new_name: old_name
                old_name: null
```

**Comment by peterspiro** [comment]
It looks like this bug may have been introduced by https://github.com/meltano/meltano/pull/7992.

**Comment by tayloramurphy** [comment]
@pnadolny13 can you take a look at this?

**Comment by pnadolny13** [comment]
@peterspiro can you share more about what your use case is for inheriting mappers?

Mappers work a little different than the extractors/loaders in that they are referred to by their mapping name vs their plugin name, so you wouldnt ever execute the `transform-columns` plugin directly. You'd reference the mapping within it so having the same mapping name across mappers isnt allowed today. It seems mappings need to be globally unique. Personally I dont know the history of why it was designed that way.

I also dont think plugin inheritance is supported by mappers, potentially because inheritance is usually for reusing a plugin with multiple different configs but in the mapper case thats already the default since `mappings` is a list.

It sounds like you're using inheritance to define and configure the same mapper in multiple files though. Maybe more details on your use case would clarify but I tested this "hack" and it does seem to work the way you want, multiple definitions of the same mapper plugin each with a single mapping config in it so you'd be able to put these in different yaml files.

```
  - name: meltano-map-transformer
    variant: meltano
    pip_url: git+https://github.com/MeltanoLabs/meltano-map-transform.git
    mappings:
      - name: rename_column
        config:
          stream_maps:
            stream_name:
              new_name: old_name
              old_name: null
  - name: meltano-map-transformer
    variant: meltano
    mappings:
      - name: rename_column2
        config:
          stream_maps:
            stream_name:
              new_name: old_name2
              old_name: null
```

**Comment by peterspiro** [comment]
Also tested on meltano 3.1.0 and I get the same behavior.

**Comment by janhoon** [comment]
Hi, I am running into the same issue. Some context on why this would be useful meltano.yaml I use as a dependency tracker then define actual configs in other files. Idea being that when I build a docker image, I can just copy the meltano.yaml and have all my dependancies ready when I copy over the other inherited configs at runtime.

Might take make an attempt at a fix if no-one else is. This would be a big benefit for how I am using meltano.

**Comment by edgarrmondragon** [comment]
> Might take make an attempt at a fix if no-one else is. This would be a big benefit for how I am using meltano.

@janhoon I probably won't be able to prioritize this in the near future, so PRs welcome!
